# Read documentation at https://async-aws.com/integration/symfony-bundle.html
async_aws:
    config:
        region: '%env(AWS_REGION)%'
#        accessKeyId: '%env(AWS_ACCESS_KEY_ID)%'
#        secretAccessKey: '%env(AWS_SECRET_ACCESS_KEY)%'


    # All installed clients are automatically autowired. Use this section to customize clients
    clients:
        s3:
            config: []
                #endpoint: '%env(resolve:AWS_ENDPOINT)%'
