gesdinet_jwt_refresh_token:
    refresh_token_class: App\Entity\RefreshToken
    ttl: 2592000 # 30 jours
    cookie:
        enabled: true
        secure: true
        http_only: true
        same_site: lax
        path: /
        domain: '%env(resolve:DOMAIN)%'
