lexik_jwt_authentication:
    api_platform:
        check_path: /auth
        username_path: email
        password_path: password
        
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    user_id_claim: email

    token_extractors:
        authorization_header:
            enabled: false
            prefix: Bearer
            name: Authorization
        cookie:
            enabled: true
            name: BEARER
